### ISSUE TITLE
GitVersion trying to fetch remotes even though tracking branches are set up

### ISSUE THREAD

**Issue by Martaver** [ParticularLabs/GitVersion#379]
Hey guys,

I'm having trouble setting up GitVersion in AppVeyor to use with a private BitBucket repo, which AppVeyor sets up automatically to use SSH.

I know in TeamCity you provided a PS script as a manual work-around to make sure all remote branches have local tracked branches so that GitVersion doesn't need to deal with SSH. I adapted that script for AppVeyor, but GitVersion is still trying to do a git fetch.

Isn't GitVersion supposed to be able to do it's job if all the branches are already available locally? Is it a bug that it's trying to fetch remote branches from origin in this case?

Log for the build from AppVeyor:

```
& {      
  $ErrorActionPreference = 'SilentlyContinue'
 
  git checkout $env:APPVEYOR_REPO_BRANCH 2>&1 | write-host
  git pull 2>&1 | write-host        
  foreach ($remoteBranch in . git branch -r) {   
    git checkout $remoteBranch.Trim().Replace("origin/", "") 2>&1 | write-host     
    git pull 2>&1 | write-host  
  }
  git checkout $env:APPVEYOR_REPO_BRANCH 2>&1 | write-host
}
Your branch is up-to-date with 'origin/develop'. 
Already up-to-date. 
Already up-to-date. 
Your branch is up-to-date with 'origin/develop'. 
Already up-to-date. 
Branch master set up to track remote branch master from origin. 
Already up-to-date. 
Your branch is up-to-date with 'origin/develop'. 
GitVersion -output buildserver
Working directory: C:\projects\ibdm-fi
Applicable build agent found: 'AppVeyor'.
One remote found (origin -> 'git@bitbucket.org:idbm/ibdm.fi.git').
Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: This transport isn't implemented. Sorry
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, Signature signature, String logMessage)
   at LibGit2Sharp.Network.DoFetch(RemoteSafeHandle remoteHandle, FetchOptions options, Signature signature, String logMessage)
   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options, Signature signature, String logMessage)
   at GitVersion.GitHelper.NormalizeGitDirectory(String gitDirectory, Authentication authentication) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\BuildServers\GitHelper.cs:line 26
   at GitVersion.Program.Run() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionExe\Program.cs:line 86
Working directory: C:\projects\ibdm-fi
Applicable build agent found: 'AppVeyor'.
One remote found (origin -> 'git@bitbucket.org:idbm/ibdm.fi.git').
Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: This transport isn't implemented. Sorry
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, Signature signature, String logMessage)
   at LibGit2Sharp.Network.DoFetch(RemoteSafeHandle remoteHandle, FetchOptions options, Signature signature, String logMessage)
   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options, Signature signature, String logMessage)
   at GitVersion.GitHelper.NormalizeGitDirectory(String gitDirectory, Authentication authentication) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\BuildServers\GitHelper.cs:line 26
   at GitVersion.Program.Run() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionExe\Program.cs:line 86
Command exited with code 1
```

**Comment by Martaver** [comment]
Any further thoughts on this? I've since tried the new version of GitVersion (3) but it still insists on fetching remotes from the origin in the NormalizeGitDirectory method. Is there any way to suppress this behavior and tell GitVersion to assume the repo is current and trust it as is?

**Comment by JakeGinnivan** [comment]
We might need to introduce a switch like `/nofetch` or something to opt out of the fetch. Otherwise I'm not really sure

**Comment by Martaver** [comment]
That would work for me. I imagine there are a lot of cases where people want to use GitVersion on a repo they cloned over SSH and this would let them handle it until LibGit2Sharp supports it.

I'll take a crack at it and submit a PR.

**Comment by Martaver** [comment]
In the mean time, I ended up solving the problem for AppVeyor by manually switching the remote to an HTTPS url prior to running GitVersion. Great idea from Feodor at AppVeyor!

The script I include is under the 'install' of my appveyor.yml:
install:   
  - git remote set-url origin https://bitbucket.org/myteam/myrepository.git

Then ensure the GITVERSION_REMOTE_USERNAME and GITVERSION_REMOTE_PASSWORD env variables are set in either the appveyor.yml file or the appveyor project configuration.

**Comment by JakeGinnivan** [comment]
As far as I know, /noFetch is in there, and got added to the Task as well. If I am wrong please post a comment and reopen this issue. Just trying to get the issues sorted out :)

**Comment by Martaver** [comment]
Yep, my pr sorted this out, go ahead and close it!
