### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by hotants** [ParticularLabs/GitVersion#409]
Hi guys,
Could you help look at this problem of "Object reference not set to an instance of an object"
Many thanks
Hotants
------------------------------
2015-03-27 07:40:34		Working directory: C:\bp457
2015-03-27 07:40:35		No specific commit specified or found, falling back to latest commit on specified branch
2015-03-27 07:40:35		Attempting to inherit branch configuration from parent branch
2015-03-27 07:40:35		HEAD is merge commit, this is likely a pull request using feature-ACSCLOUD-103-AlertDetection as base
2015-03-27 07:42:15		Found possible parent branches: origin/Feature/XXXX-103-AlertDetection, origin/feature-XXXX-103-AlertDetection
2015-03-27 07:42:15		Failed to inherit Increment branch configuration, ended up with: origin/Feature/XXXX-103-AlertDetection, origin/feature-XXXX-103-AlertDetection

Falling back to develop branch config
2015-03-27 07:42:15		An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitVersion.BranchConfigurationCalculator.<>c__DisplayClass3.<GetBranchConfiguration>b__0(KeyValuePair`2 b) in c:\develop\OpenSource\GitVersion-anobleperson\GitVersionCore\BranchConfigurationCalculator.cs:line 13
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at GitVersion.BranchConfigurationCalculator.GetBranchConfiguration(Commit currentCommit, IRepository repository, Boolean onlyEvaluateTrackedBranches, Config config, Branch currentBranch) in c:\develop\OpenSource\GitVersion-anobleperson\GitVersionCore\BranchConfigurationCalculator.cs:line 13
   at GitVersion.BranchConfigurationCalculator.InheritBranchConfiguration(Boolean onlyEvaluateTrackedBranches, IRepository repository, Commit currentCommit, Branch currentBranch, KeyValuePair`2 keyValuePair, BranchConfig branchConfiguration, Config config) in c:\develop\OpenSource\GitVersion-anobleperson\GitVersionCore\BranchConfigurationCalculator.cs:line 114
   at GitVersion.BranchConfigurationCalculator.GetBranchConfiguration(Commit currentCommit, IRepository repository, Boolean onlyEvaluateTrackedBranches, Config config, Branch currentBranch) in c:\develop\OpenSource\GitVersion-anobleperson\GitVersionCore\BranchConfigurationCalculator.cs:line 26
   at GitVersion.GitVersionContext.CalculateEffectiveConfiguration() in c:\develop\OpenSource\GitVersion-anobleperson\GitVersionCore\GitVersionContext.cs:line 79
   at GitVersion.GitVersionContext..ctor(IRepository repository, Branch currentBranch, Config configuration, Boolean onlyEvaluateTrackedBranches, String commitId) in c:\develop\OpenSource\GitVersion-anobleperson\GitVersionCore\GitVersionContext.cs:line 55
   at GitVersion.GitVersionContext..ctor(IRepository repository, Config configuration, Boolean isForTrackingBranchOnly, String commitId) in c:\develop\OpenSource\GitVersion-anobleperson\GitVersionCore\GitVersionContext.cs:line 14
   at GitVersion.Program.Run()

**Comment by JakeGinnivan** [comment]
Could you please post the results of `git log --graph --abbrev-commit --decorate --date=relative --all --max-count=100`

Hopefully we should be able to see enough of the graph to figure what is going on in 100 commits. Somehow the feature branch has been tracked multiple times, I want to try and create a reproduction test based off your commit graph

**Comment by hotants** [comment]
Hi JakeGinnivan,  
      Many thanks, here is the result:
C:\XX103> git log --graph --abbrev-commit --decorate --date=relative --all --max
-count=100
WARNING: terminal is not fully functional
*   commit f4d4689 (origin/feature-XXXX-103-AlertDetection)
|\  Merge: 5268290 ba89f1e
| | Author: denny song <denny.song@MyCompany.com>
| | Date:   2 days ago
| |
| |     Merge remote-tracking branch 'origin/feature-XXXX-103-AlertDetection

| |
| *   commit ba89f1e
| |\  Merge: ac52f68 100e41b
| | | Author: Santosh Karanam <santosh.karanam@MyCompany.com>
| | | Date:   2 days ago
| | |
| | |     Merge remote-tracking branch 'origin/feature-XXXX-459-EventHubSupp

| | |
| | * commit 100e41b (origin/feature-XXXX-459-EventHubSupportInValet)
| | | Author: Ranjith Keloth <ranjith.keloth@MyCompany.com>
| | | Date:   3 days ago
| | |
| | |     XXXX-459 Made deployment script changes for new analytics group an

| | |
| | * commit 582dbe4
| | | Author: peng he <peng.he@MyCompany.com>
| | | Date:   3 days ago
| | |
:

**Comment by JakeGinnivan** [comment]
That looks incomplete, it is only showing 3 commits. Can you put it in a gist as well? (https://gist.github.com/)

**Comment by JakeGinnivan** [comment]
Also if you surround it with three backticks it will not try and format it. Or indent it by 4 spaces in a text editor before pasting into gist

**Comment by hotants** [comment]
Please find it from https://gist.github.com/anonymous/0891af15b64f533d37bd 
Thanks

**Comment by yannisgu** [comment]
The NullReferenceException is coming from https://github.com/ParticularLabs/GitVersion/blob/master/GitVersionCore/BranchConfigurationCalculator.cs#L120

```
var hasDevelop = repository.FindBranch("develop") != null; // Not null because origin/develop exists
...
... repository.Branches[branchName] /// null because 'develop' doesn't exist
```

**Comment by JakeGinnivan** [comment]
@yannisgu nice work.. That does look like the issue!

**Comment by JakeGinnivan** [comment]
@hotants thanks for reporting, should be released soon!
