### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by distantcam** [ParticularLabs/GitVersion#463]
When building off a tagged head I get the following error.

```
1>MSBUILD : error : Error occurred: System.ArgumentException: An item with the same key has already been added.
1>MSBUILD : error :    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
1>MSBUILD : error :    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
1>MSBUILD : error :    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
1>MSBUILD : error :    at GitVersion.LastMinorVersionFinder.GetTimeStampFromTag(IRepository repository, Config configuration, Commit targetCommit) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\LastMinorVersionFinder.cs:line 33
1>MSBUILD : error :    at GitVersion.LastMinorVersionFinder.Execute(IRepository repo, Config configuration, Commit commit) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\LastMinorVersionFinder.cs:line 21
1>MSBUILD : error :    at VersionCache.GetVersion(String gitDirectory, Config configuration) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionTask\VersionCache.cs:line 29
1>MSBUILD : error :    at VersionAndBranchFinder.TryGetVersion(String directory, CachedVersion& versionAndBranch, Config configuration) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionTask\VersionAndBranchFinder.cs:line 33
1>MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.InnerExecute() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionTask\WriteVersionInfoToBuildLog.cs:line 54
1>MSBUILD : error :    at GitVersionTask.WriteVersionInfoToBuildLog.Execute() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionTask\WriteVersionInfoToBuildLog.cs:line 31
```

GitVersion 2.0.1
Happens in GitFlow mode.

**Comment by distantcam** [comment]
This seems to be fixed in v3.
